### ISSUE TITLE
Address performance / caching issues more explicitly

### ISSUE THREAD

**Issue by mnot** [w3ctag/web-https#10]
as per David:

>  I really think that this paragraph needs considerable more text:
> 
> "We recognize that as this policy is implemented, it will further reduce the utility of shared HTTP caches -- a trend started by the transition of many popular Web sites to HTTPS (and thus, loss of a high proportion of cache hits). This is an unfortunate outcome, and we should continue to examine how efficiency can be gained without compromising security.”
> 
> As I think many fear that if they go to HTTPS their users’ perceived performance will go to hell.

**Comment by timbl** [comment]
A web app's performance drops when it is run over HTTPS as opposed to HTTP.     Suggest you include a comparison chart of the number of round trips necessary for (a) HTTP (b) HTTPS with client & server cert (c) HTTPS with only server cert for the first request, and for subsequent ones, to first byte returned.  That puts a lower limit on the response time.

**Comment by mnot** [comment]
There are a _lot_ of variables, depending on TLS version, extensions in use, etc.  It's also likely to be changing over time (e.g., TLS/1.3 is in the works now, and will have 0-RT and 1-RT modes).

A lot of this is covered by https://istlsfastyet.com -- would a link to that and a brief summary do the trick?

**Comment by domenic** [comment]
+1 for istlsfastyet, it's a great source for clearing up the common misconception that TLS is slower (and showing how to configure/upgrade your server to bring it into the modern era where that isn't true any longer). Might also be worth mentioning that with modern browsers that implement HTTP2, TLS will often be faster?

**Comment by wycats** [comment]
@domenic I think HTTP2 is important here. Perceived performance on web apps is actually far more about techniques to reduce blocking connections and round trips than (often flaky) caches.

A lot of people use caching techniques (varnish, squid, or CDNs) that work effectively behind HTTPS, and nobody I know considers web proxies/caches to be worth the trouble they introduce (in aggregate) via bugs.

**Comment by mnot** [comment]
Been adjusted a few times, then rewritten. Closing for now.
