### ISSUE TITLE
Small editorial suggestions

### ISSUE THREAD

**Issue by dbooth-boston** [w3ctag/web-https#13]
1. s/use of HTTPS URLs instead of HTTP ones/use of "https:" URLs instead of "http:" URLs/
   because "http:" and "https:" refer to URI schemes, whereas "HTTP" and "HTTPS" refer to protocols.
2. In the Motivation section, the sentence beginning "This is because security" should NOT be starting a new paragraph.
3. s/this means using HTTPS URLs/this means using "https:" URLs/
4. Suggest: s/an image request in the clear/an image request "in the clear" (i.e., unencrypted)/
   because "in the clear" is security jargon that not all readers may know.
5. Typo: s/ communiation/commnication/
6. Typo: s/compromising on their/compromising their/
7. s/specifications; the most immediate/specifications.  The most immediate/
8. s/use of HTTPS URLs instead of HTTP ones/use of "https:" URLs instead of "http:" URLs/
9. s/The Web Applications Security Working Group/The Web Applications Security Working Group (WebAppSec)/
   because the term WebAppSec is used later to refer to this group.
10. s/providing that there is no loss/provided that there is no loss/

**Comment by mnot** [comment]
Thanks. In the future, consider a pull request? :)
