### ISSUE TITLE
"best --- if imperfectly ---"

### ISSUE THREAD

**Issue by domenic** [w3ctag/web-https#15]
Instead of "These important properties of authentication, integrity and confidentiality are best — if imperfectly — provided on the Web by..."

I'd suggest

"These important properties of authentication, integrity and confidentiality on the Web are strongly bolstered by ..."

**Comment by mnot** [comment]
I don't know if I like "strongly bolstered by"; it implies that there's _some_ level of them without TLS, which isn't true.

**Comment by domenic** [comment]
Hmm. "These important properties of authentication, integrity and confidentiality on the Web need, as a prerequisite, ..."?

**Comment by annevk** [comment]
I think confidentiality is overstated here and elsewhere. Researchers have shown that with traffic analysis you can derive a great deal, e.g. what article is being read on a site, what a user is looking at on a map, etc. There is confidentiality for smaller aspects, such as usernames and passwords, but not really fully confidentiality.

Whereas authentication and integrity do not require any caveats to my knowledge.

**Comment by mnot** [comment]
That's why I had " -- if imperfectly -- " in there. What we're saying here is that TLS is our best hope for a reasonable baseline for security.

**Comment by domenic** [comment]
After thinking about it, the real reason I opened this issue is that it's too easy to read "imperfectly" as "flawed." As in, given that this is one of the first sentences in the document, my takeaway is something like "TLS is a flawed mechanism for authentication, integrity and confidentiality."

If people actually interpreted "imperfectly" as "not up to theoretical perfection," then there'd be no problem. (Although if that were the case, I think the phrase would be largely redundant here, as no software lives up to that ideal.) Instead I think it's generally read more as "flawed," which seems not what you're trying to communicate.

**Comment by mnot** [comment]
That makes sense. Not sure how to improve it, though.

**Comment by annevk** [comment]
If you say "currently best" and leave "if imperfectly" out that might be good enough?

**Comment by annevk** [comment]
It still seems good to dig into each of these a bit and explain to what extend they are provided, but...

**Comment by ylafon** [comment]
Well, if you remove the hand-waving "imperfect" word, pointing some issues with TLS would be good (like clear hostname in SNI, DNS, etc...) best would be to point to work in progress to tackle some issues. But saying that TLS is the panacea (as it might be implied by removing "if imperfectly") would be wrong and misleading.

**Comment by domenic** [comment]
I don't think removing "if imperfectly" has any implications of panacea.

"HTTP provides -- if imperfectly -- an application protocol for distributed, collaborative, hypermedia information systems."

"Microsoft Visual Studio is an integrated development environment (IDE) from Microsoft. It is used -- imperfectly -- to develop computer programs for Microsoft Windows, as well as web sites, web applications and web services."

"HTML describes the structure of a Website semantically along with cues for presentation -- albeit imperfectly."

(using Wikipedia as my source for original text)

Saying technology is imperfect is basically tautological.

On the other hand, I _love_ @annevk's suggestion of "currently best". I think it conveys the intended sentiment much better.

**Comment by annevk** [comment]
@ylafon claiming confidentiality seems the most problematic, indeed. On https://wiki.whatwg.org/wiki/TLS I used "increased confidentiality".

So perhaps "These important properties of authentication, integrity, and increased confidentiality are currently best provided on the web by TLS."

**Comment by mnot** [comment]
LGTM.

**Comment by ylafon** [comment]
@annevk Yes, that sounds right. Thanks!
