### ISSUE TITLE
"Securing the Web" is too general

### ISSUE THREAD

**Issue by annevk** [w3ctag/web-https#16]
I think overall this is well written. But I'd prefer that instead of things like "actively prefer secure communication" it would be more precise. E.g. "actively prefer communication using authenticated encryption".

Flushing out TLS and the CA system would be great too, but I guess that might be a bit much.

**Comment by mnot** [comment]
I've been trying to avoid making a definite statement here about OppSec, because that's really a decision for the IETF folks + perhaps WebAppSec; I don't want the TAG dictating fine details of security (at least too much! :)

**Comment by annevk** [comment]
In motivation you already cite authentication and integrity as being important. You also cite confidentiality, but that could be elaborated since TLS only does that in part.

Saying that much clearly seems important since we don't want to endorse HTTP + Web Crypto or (o_O) HTTP auth as enabling "security".

**Comment by mnot** [comment]
I have a really hard time seeing how this document could be interpreted to endorse HTTP + WebCrypto -- it says HTTPS is the best solution, and it levers into the powerful features discussion.

**Comment by annevk** [comment]
Given the weird ass discussion on www-tag, I was just thinking that perhaps we should be more explicit about some of the characteristics. Anyway, your call I guess.
