### ISSUE TITLE
Broken links in SOTD

### ISSUE THREAD

**Issue by gosko** [w3ctag/web-https#23]
Hi, there are a couple broken links in [the sotd of Securing the Web](https://w3ctag.github.io/web-https/#sotd): [Additional TAG findings](https://w3ctag.github.io/2001/tag/findings) is returning a 404, and the [\#AWWW](https://w3ctag.github.io/web-https/\#AWWW) fragment does not exist.

**Comment by ylafon** [comment]
Fixed bt [579391d](https://github.com/w3ctag/web-https/commit/579391d0fcf1bff0e7902c68abddf3e359e0ee12) and 310bae524cb012ea9bc0d19c29100b8c3ea8802f
