### ISSUE TITLE
Expand scope to SMTP / other protocols?

### ISSUE THREAD

**Issue by diracdeltas** [w3ctag/web-https#3]
> These important properties of authentication, integrity and confidentiality are best — if imperfectly — provided on the Web by Transport Layer Security (TLS) [[RFC5246]], through use of HTTPS URLs. 

RFC5246 is application protocol-independent, which suggests that maybe this document will be as well, but it really only covers HTTPS. Should it also cover SMTP transit encryption (STARTTLS usually), given that email is also a large fraction of internet traffic?

**Comment by diracdeltas** [comment]
Probably more relevant: the "Prefer Secure Origins" doc defines secure origin as `wss://` and local origins, in addition to `https://`. I would propose the following to make it more clear that HTTPS is not the only secure protocol on the web, though it's the focus of the document:

https://github.com/w3ctag/web-https/blob/gh-pages/index.html#L63 - replace "HTTPS URLs" with "secure URL schemes such as HTTPS".

**Comment by mnot** [comment]
I want to be a bit careful here, because "secure URL schemes" implies it's good practice to associate security properties with URL schemes -- a contentious topic in itself.

**Comment by mnot** [comment]
Closing; feel free to discuss more / reopen.
