### ISSUE TITLE
Align with POWER terminology

### ISSUE THREAD

**Issue by sideshowbarker** [w3ctag/web-https#5]
I think https://w3c.github.io/webappsec/specs/powerfulfeatures/ is the latest actively maintained version of the ideas initially outlined in the Chromium "Prefer Secure Origins For Powerful New Features" doc. So it seems like at this point the TAG might better be reading and referencing the https://w3c.github.io/webappsec/specs/powerfulfeatures/ doc rather than that the older one—and using the terminology in the newer doc, like "sufficiently secure context" rather (I guess) than "secure origin".

**Comment by mnot** [comment]
We do reference it -- the only mention of the Chromium document is in the acknowledgements. We ack the Chromium document because it was the one that inspired this, not the newer one.

**Comment by sideshowbarker** [comment]
Ok, yeah I see the reference listed now but I guess I was expecting to see some text in the body of the finding saying something like, "This document uses the following terms that are defined in [Powerful features]."

Relevant to that, the finding currntly uses the term "secure origin", which is by design not defined or used at all in the powerful-features doc; instead the powerful-features doc uses "potentially secure origin" and "sufficiently secure context".

**Comment by mnot** [comment]
yep, makes sense.

**Comment by mnot** [comment]
Looking at this again, I'm inclined to leave as-is; adding more precise terminology seems entirely appropriate for the POWER document -- as a technical specification -- but I don't see how it helps in a higher-level policy document.

**Comment by sideshowbarker** [comment]
> Looking at this again, I'm inclined to leave as-is; adding more precise terminology seems entirely appropriate for the POWER document -- as a technical specification -- but I don't see how it helps in a higher-level policy document.

Fair enough. I was mainly just challenging the use of term **secure origin** without qualification; by that I mean, in contrast to **potentially secure origin**.

It's my understanding that the POWER editor @mikewest is intentionally not ever using the term "secure origin" without qualification in POWER. At least I believe that @annevk (who I think Mike is in close communication with around this stuff) has argued persuasively against using "secure origin", and Anne's insights and feedback have informed other parts of the spec.

**Comment by mikewest** [comment]
I'm staying away from the bare "secure" because it will lead to confusion. For example: is unauthenticated HTTP "secure"? No, of course not, but there's substantial argument on that point (mostly from people who are wrong :) ). Qualifying just moves the debate to "sufficient", of course, but it's at least a term that we're clearly defining.

I'm ambivalent regarding the term in the TAG document. As a policy statement, it's probably fine to be loose with the formal terminology. _shrug_

**Comment by sideshowbarker** [comment]
> I'm ambivalent regarding the term in the TAG document. As a policy statement, it's probably fine to be loose with the formal terminology. shrug

OK. I don't feel strongly about it and as I said earlier here, I just wanted to challenge the wording. But at this point, challenged answered—I'm satisfied with @mnot's response, and in general agree that a policy document doesn't need to be subjected to the same level of bikeshedding^wscrutiny as a spec.

**Comment by annevk** [comment]
Saying secure origins still seems wrong though if we actually care about a combination of origin, transport, and ancestor browsing contexts.

**Comment by annevk** [comment]
E.g. you can't claim anything about "https://google.com/" without fetching it first and therefore all the talk about origin is needlessly confusing.
