### ISSUE TITLE
Explicitly address "but I don't need HTTPS, because my site is simple"?

### ISSUE THREAD

**Issue by domenic** [w3ctag/web-https#9]
There's persistent confusion in various forms by people claiming that because their site is static or does not use cookies, they don't need HTTPS. (Or, more amusingly, claiming that their home-cooked authentication scheme is good enough.) It may be useful to explicitly address this, perhaps with a sentence or two that links to a larger resource like https://sites.google.com/a/chromium.org/dev/Home/chromium-security/education/tls?pli=1#TOC-The-only-security-guarantee-TLS-provides-is-confidentiality or similar.

Related blink-dev posts:
- https://groups.google.com/a/chromium.org/d/msg/blink-dev/DHQLv76QaEM/TdhGW9qi9UAJ
- https://groups.google.com/a/chromium.org/d/msg/blink-dev/DHQLv76QaEM/do5rrsTsk5AJ
- https://groups.google.com/a/chromium.org/d/msg/blink-dev/DHQLv76QaEM/oQgaGo8jqsoJ

**Comment by annevk** [comment]
https://wiki.whatwg.org/wiki/TLS has a set of reasons plus a large set of linked resources to draw from.

**Comment by wycats** [comment]
@annevk the only reasons I can see on this list that would be persuasive are Google ranking and new platform features, which are "stick" not "carrot" answers and kind of beg the question.

What are our best arguments for HTTPS that are intrinsic, and not simply the result of vendors trying to foist HTTPS on people.

**Comment by annevk** [comment]
Integrity is not persuasive? Seems like the kind of thing that's especially valuable for static content.

**Comment by diracdeltas** [comment]
Chris Palmer and I wrote something for a similar audience, feel free to borrow language: https://www.eff.org/https-everywhere/deploying-https

**Comment by domenic** [comment]
The current draft contains

> Notably, these risks are just as present for users of "plain" Web sites as they are for those using more sophisticated, interactive sites. 

I think it could benefit from a link or two from the OP, or (optionally) an example, e.g. "As a simple example, malicious modifications to an informational site about a company could have drastic effects on its stock price."
